copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt
copy w.txt w%random%.txt